# Generated by Django 3.2.13 on 2022-08-18 21:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='issue_description',
            field=tinymce.models.HTMLField(blank=True, max_length=25000, null=True),
        ),
    ]
