# Generated by Django 3.2.13 on 2022-08-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_alter_ticket_issue_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imap_server', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('email_password', models.CharField(max_length=100)),
                ('imap_port', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='OutgoinEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_reply_email_name', models.CharField(max_length=255)),
                ('support_reply_email', models.EmailField(max_length=255)),
                ('send_auto_email_on_ticket_creation', models.BigIntegerField(default=True)),
                ('code_for_automated_reply', models.TextField(max_length=25000)),
                ('end_auto_email_on_agent_reply', models.BigIntegerField(default=True)),
                ('code_for_agent_reply', models.TextField(max_length=25000)),
                ('code_place_holders', models.TextField(max_length=25000)),
            ],
            options={
                'verbose_name_plural': 'Support Email Setup - (Outgoing)',
            },
        ),
    ]
