# Generated by Django 3.2.13 on 2022-08-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_imapsettings_outgoinemailsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imapsettings',
            options={'verbose_name_plural': 'Imap Email Setup - (Incoming)'},
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='end_auto_email_on_agent_reply',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='send_auto_email_on_ticket_creation',
            field=models.BooleanField(default=True),
        ),
    ]
