# Generated by Django 3.2.13 on 2022-08-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_auto_20220819_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoinemailsettings',
            name='email_backed',
            field=models.CharField(default='smtp', max_length=100),
        ),
        migrations.AddField(
            model_name='outgoinemailsettings',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='outgoinemailsettings',
            name='email_password',
            field=models.CharField(default='xdofqrtncuimlewm', max_length=255),
        ),
        migrations.AddField(
            model_name='outgoinemailsettings',
            name='email_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='support_reply_email',
            field=models.EmailField(default='titusowuor30@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='support_reply_email_name',
            field=models.CharField(default='ICT Helpdesk', max_length=255),
        ),
    ]
