# Generated by Django 3.2.13 on 2022-08-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_auto_20220819_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoinemailsettings',
            name='fail_silently',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='outgoinemailsettings',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
