# Generated by Django 3.2.13 on 2022-08-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_auto_20220819_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoinemailsettings',
            name='auto_email_on_agent_assignment',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='outgoinemailsettings',
            name='code_for_automated_assign',
            field=models.TextField(blank=True, max_length=25000, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='code_for_agent_reply',
            field=models.TextField(blank=True, max_length=25000, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='code_for_automated_reply',
            field=models.TextField(blank=True, max_length=25000, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='code_place_holders',
            field=models.TextField(blank=True, max_length=25000, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='email_backed',
            field=models.CharField(blank=True, default='smtp', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='email_password',
            field=models.CharField(blank=True, default='xdofqrtncuimlewm', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='email_port',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='end_auto_email_on_agent_reply',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='fail_silently',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='send_auto_email_on_ticket_creation',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='support_reply_email',
            field=models.EmailField(blank=True, default='titusowuor30@gmail.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='support_reply_email_name',
            field=models.CharField(blank=True, default='ICT Helpdesk', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='outgoinemailsettings',
            name='use_tls',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
