# Generated by Django 3.2.13 on 2022-08-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_auto_20220821_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outgoinemailsettings',
            old_name='auto_email_on_agent_assignment',
            new_name='send_auto_email_on_agent_assignment',
        ),
        migrations.RenameField(
            model_name='outgoinemailsettings',
            old_name='end_auto_email_on_agent_reply',
            new_name='send_auto_email_on_agent_reply',
        ),
    ]
