# Generated by Django 3.2.13 on 2022-08-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0008_auto_20220821_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoinemailsettings',
            name='auto_assign_tickets',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
