# Generated by Django 3.2.13 on 2022-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0009_outgoinemailsettings_auto_assign_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='imapsettings',
            name='auto_import_mails_as_tickets',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
