# Generated by Django 3.2.13 on 2022-08-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0011_auto_20220825_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Normal', max_length=100),
        ),
    ]
