# Generated by Django 3.2.13 on 2022-08-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0014_auto_20220825_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_priority',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Normal', 'Normal'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=100, null=True),
        ),
    ]
